<?php

namespace DoctrineProxies\__CG__\App\Models\Entities;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Nekretnina extends \App\Models\Entities\Nekretnina implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Models\\Entities\\Nekretnina' . "\0" . 'idn', '' . "\0" . 'App\\Models\\Entities\\Nekretnina' . "\0" . 'kvadratura', '' . "\0" . 'App\\Models\\Entities\\Nekretnina' . "\0" . 'brSoba', '' . "\0" . 'App\\Models\\Entities\\Nekretnina' . "\0" . 'godinaIzgradnje', '' . "\0" . 'App\\Models\\Entities\\Nekretnina' . "\0" . 'sprat', '' . "\0" . 'App\\Models\\Entities\\Nekretnina' . "\0" . 'ukupnaSpratnost', '' . "\0" . 'App\\Models\\Entities\\Nekretnina' . "\0" . 'parking', '' . "\0" . 'App\\Models\\Entities\\Nekretnina' . "\0" . 'stanje', '' . "\0" . 'App\\Models\\Entities\\Nekretnina' . "\0" . 'grejanje', '' . "\0" . 'App\\Models\\Entities\\Nekretnina' . "\0" . 'mesecniTroskovi', '' . "\0" . 'App\\Models\\Entities\\Nekretnina' . "\0" . 'opis', '' . "\0" . 'App\\Models\\Entities\\Nekretnina' . "\0" . 'status', '' . "\0" . 'App\\Models\\Entities\\Nekretnina' . "\0" . 'mikrolokacija', '' . "\0" . 'App\\Models\\Entities\\Nekretnina' . "\0" . 'opstina', '' . "\0" . 'App\\Models\\Entities\\Nekretnina' . "\0" . 'agencija', '' . "\0" . 'App\\Models\\Entities\\Nekretnina' . "\0" . 'ulica', '' . "\0" . 'App\\Models\\Entities\\Nekretnina' . "\0" . 'karakteristike', '' . "\0" . 'App\\Models\\Entities\\Nekretnina' . "\0" . 'oglasivac', '' . "\0" . 'App\\Models\\Entities\\Nekretnina' . "\0" . 'tip', '' . "\0" . 'App\\Models\\Entities\\Nekretnina' . "\0" . 'gradid', '' . "\0" . 'App\\Models\\Entities\\Nekretnina' . "\0" . 'kupci'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Models\\Entities\\Nekretnina' . "\0" . 'idn', '' . "\0" . 'App\\Models\\Entities\\Nekretnina' . "\0" . 'kvadratura', '' . "\0" . 'App\\Models\\Entities\\Nekretnina' . "\0" . 'brSoba', '' . "\0" . 'App\\Models\\Entities\\Nekretnina' . "\0" . 'godinaIzgradnje', '' . "\0" . 'App\\Models\\Entities\\Nekretnina' . "\0" . 'sprat', '' . "\0" . 'App\\Models\\Entities\\Nekretnina' . "\0" . 'ukupnaSpratnost', '' . "\0" . 'App\\Models\\Entities\\Nekretnina' . "\0" . 'parking', '' . "\0" . 'App\\Models\\Entities\\Nekretnina' . "\0" . 'stanje', '' . "\0" . 'App\\Models\\Entities\\Nekretnina' . "\0" . 'grejanje', '' . "\0" . 'App\\Models\\Entities\\Nekretnina' . "\0" . 'mesecniTroskovi', '' . "\0" . 'App\\Models\\Entities\\Nekretnina' . "\0" . 'opis', '' . "\0" . 'App\\Models\\Entities\\Nekretnina' . "\0" . 'status', '' . "\0" . 'App\\Models\\Entities\\Nekretnina' . "\0" . 'mikrolokacija', '' . "\0" . 'App\\Models\\Entities\\Nekretnina' . "\0" . 'opstina', '' . "\0" . 'App\\Models\\Entities\\Nekretnina' . "\0" . 'agencija', '' . "\0" . 'App\\Models\\Entities\\Nekretnina' . "\0" . 'ulica', '' . "\0" . 'App\\Models\\Entities\\Nekretnina' . "\0" . 'karakteristike', '' . "\0" . 'App\\Models\\Entities\\Nekretnina' . "\0" . 'oglasivac', '' . "\0" . 'App\\Models\\Entities\\Nekretnina' . "\0" . 'tip', '' . "\0" . 'App\\Models\\Entities\\Nekretnina' . "\0" . 'gradid', '' . "\0" . 'App\\Models\\Entities\\Nekretnina' . "\0" . 'kupci'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Nekretnina $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdn()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdn();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdn', []);

        return parent::getIdn();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdn($idn)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdn', [$idn]);

        return parent::setIdn($idn);
    }

    /**
     * {@inheritDoc}
     */
    public function getKvadratura()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getKvadratura', []);

        return parent::getKvadratura();
    }

    /**
     * {@inheritDoc}
     */
    public function setKvadratura($kvadratura)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setKvadratura', [$kvadratura]);

        return parent::setKvadratura($kvadratura);
    }

    /**
     * {@inheritDoc}
     */
    public function getBrSoba()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBrSoba', []);

        return parent::getBrSoba();
    }

    /**
     * {@inheritDoc}
     */
    public function setBrSoba($brSoba)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBrSoba', [$brSoba]);

        return parent::setBrSoba($brSoba);
    }

    /**
     * {@inheritDoc}
     */
    public function getGodinaIzgradnje()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGodinaIzgradnje', []);

        return parent::getGodinaIzgradnje();
    }

    /**
     * {@inheritDoc}
     */
    public function setGodinaIzgradnje($godinaIzgradnje)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGodinaIzgradnje', [$godinaIzgradnje]);

        return parent::setGodinaIzgradnje($godinaIzgradnje);
    }

    /**
     * {@inheritDoc}
     */
    public function getSprat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSprat', []);

        return parent::getSprat();
    }

    /**
     * {@inheritDoc}
     */
    public function setSprat($sprat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSprat', [$sprat]);

        return parent::setSprat($sprat);
    }

    /**
     * {@inheritDoc}
     */
    public function getUkupnaSpratnost()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUkupnaSpratnost', []);

        return parent::getUkupnaSpratnost();
    }

    /**
     * {@inheritDoc}
     */
    public function setUkupnaSpratnost($ukupnaSpratnost)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUkupnaSpratnost', [$ukupnaSpratnost]);

        return parent::setUkupnaSpratnost($ukupnaSpratnost);
    }

    /**
     * {@inheritDoc}
     */
    public function getParking()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getParking', []);

        return parent::getParking();
    }

    /**
     * {@inheritDoc}
     */
    public function setParking($parking)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setParking', [$parking]);

        return parent::setParking($parking);
    }

    /**
     * {@inheritDoc}
     */
    public function getStanje()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStanje', []);

        return parent::getStanje();
    }

    /**
     * {@inheritDoc}
     */
    public function setStanje($stanje)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStanje', [$stanje]);

        return parent::setStanje($stanje);
    }

    /**
     * {@inheritDoc}
     */
    public function getGrejanje()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGrejanje', []);

        return parent::getGrejanje();
    }

    /**
     * {@inheritDoc}
     */
    public function setGrejanje($grejanje)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGrejanje', [$grejanje]);

        return parent::setGrejanje($grejanje);
    }

    /**
     * {@inheritDoc}
     */
    public function getMesecniTroskovi()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMesecniTroskovi', []);

        return parent::getMesecniTroskovi();
    }

    /**
     * {@inheritDoc}
     */
    public function setMesecniTroskovi($mesecniTroskovi)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMesecniTroskovi', [$mesecniTroskovi]);

        return parent::setMesecniTroskovi($mesecniTroskovi);
    }

    /**
     * {@inheritDoc}
     */
    public function getOpis()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOpis', []);

        return parent::getOpis();
    }

    /**
     * {@inheritDoc}
     */
    public function setOpis($opis)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOpis', [$opis]);

        return parent::setOpis($opis);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', []);

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', [$status]);

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getMikrolokacija()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMikrolokacija', []);

        return parent::getMikrolokacija();
    }

    /**
     * {@inheritDoc}
     */
    public function setMikrolokacija($mikrolokacija)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMikrolokacija', [$mikrolokacija]);

        return parent::setMikrolokacija($mikrolokacija);
    }

    /**
     * {@inheritDoc}
     */
    public function getOpstina()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOpstina', []);

        return parent::getOpstina();
    }

    /**
     * {@inheritDoc}
     */
    public function setOpstina($opstina)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOpstina', [$opstina]);

        return parent::setOpstina($opstina);
    }

    /**
     * {@inheritDoc}
     */
    public function getAgencija()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAgencija', []);

        return parent::getAgencija();
    }

    /**
     * {@inheritDoc}
     */
    public function setAgencija($agencija)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAgencija', [$agencija]);

        return parent::setAgencija($agencija);
    }

    /**
     * {@inheritDoc}
     */
    public function getUlica()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUlica', []);

        return parent::getUlica();
    }

    /**
     * {@inheritDoc}
     */
    public function setUlica($ulica)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUlica', [$ulica]);

        return parent::setUlica($ulica);
    }

    /**
     * {@inheritDoc}
     */
    public function getKarakteristike()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getKarakteristike', []);

        return parent::getKarakteristike();
    }

    /**
     * {@inheritDoc}
     */
    public function setKarakteristike($karakteristike)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setKarakteristike', [$karakteristike]);

        return parent::setKarakteristike($karakteristike);
    }

    /**
     * {@inheritDoc}
     */
    public function getOglasivac()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOglasivac', []);

        return parent::getOglasivac();
    }

    /**
     * {@inheritDoc}
     */
    public function setOglasivac($oglasivac)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOglasivac', [$oglasivac]);

        return parent::setOglasivac($oglasivac);
    }

    /**
     * {@inheritDoc}
     */
    public function getTip()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTip', []);

        return parent::getTip();
    }

    /**
     * {@inheritDoc}
     */
    public function setTip($tip)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTip', [$tip]);

        return parent::setTip($tip);
    }

    /**
     * {@inheritDoc}
     */
    public function getGradid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGradid', []);

        return parent::getGradid();
    }

    /**
     * {@inheritDoc}
     */
    public function setGradid($gradid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGradid', [$gradid]);

        return parent::setGradid($gradid);
    }

    /**
     * {@inheritDoc}
     */
    public function getKupci()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getKupci', []);

        return parent::getKupci();
    }

    /**
     * {@inheritDoc}
     */
    public function setKupci($kupci)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setKupci', [$kupci]);

        return parent::setKupci($kupci);
    }

}
